const ADJECTIVES = [
  "amber",
  "bold",
  "bright",
  "calm",
  "clever",
  "cold",
  "crisp",
  "daring",
  "dark",
  "deep",
  "dry",
  "eager",
  "early",
  "even",
  "fair",
  "fast",
  "fierce",
  "firm",
  "flat",
  "fleet",
  "free",
  "fresh",
  "full",
  "gentle",
  "grand",
  "grave",
  "great",
  "green",
  "grim",
  "happy",
  "hardy",
  "harsh",
  "keen",
  "kind",
  "late",
  "lean",
  "light",
  "lofty",
  "lone",
  "loud",
  "lucid",
  "lucky",
  "mild",
  "noble",
  "north",
  "plain",
  "prime",
  "proud",
  "pure",
  "quick",
  "quiet",
  "rapid",
  "rare",
  "rich",
  "rosy",
  "round",
  "royal",
  "sharp",
  "silent",
  "sleek",
  "slim",
  "slow",
  "smart",
  "soft",
  "solid",
  "sparse",
  "still",
  "stout",
  "strange",
  "strong",
  "sure",
  "swift",
  "tall",
  "tame",
  "tense",
  "tidy",
  "tight",
  "true",
  "vast",
  "vivid",
  "warm",
  "wild",
  "wise",
  "witty",
  "young",
];

const NOUNS = [
  "anchor",
  "apex",
  "apple",
  "apricot",
  "arc",
  "ash",
  "bay",
  "beam",
  "birch",
  "blaze",
  "bloom",
  "boulder",
  "brook",
  "canyon",
  "cedar",
  "cliff",
  "cloud",
  "clover",
  "comet",
  "coral",
  "crane",
  "creek",
  "crest",
  "crystal",
  "dawn",
  "delta",
  "dune",
  "dust",
  "ember",
  "falcon",
  "fern",
  "field",
  "flint",
  "fog",
  "forge",
  "frost",
  "gale",
  "gate",
  "glade",
  "grove",
  "hawk",
  "heath",
  "hedge",
  "hill",
  "hollow",
  "heron",
  "iris",
  "jade",
  "kettle",
  "lake",
  "lantern",
  "larch",
  "lark",
  "leaf",
  "ledge",
  "light",
  "lily",
  "linden",
  "lynx",
  "maple",
  "marsh",
  "mast",
  "meadow",
  "mesa",
  "mist",
  "moon",
  "moss",
  "nebula",
  "oak",
  "orbit",
  "peak",
  "pine",
  "plain",
  "pond",
  "prism",
  "quartz",
  "rain",
  "reed",
  "ridge",
  "river",
  "rook",
  "root",
  "sage",
  "shore",
  "sky",
  "slate",
  "snow",
  "spark",
  "spire",
  "spring",
  "star",
  "stone",
  "storm",
  "stream",
  "summit",
  "tide",
  "trail",
  "vale",
  "vapor",
  "vine",
  "wave",
  "willow",
  "wind",
];

export function generateSessionName(): string {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  return `${adjective}-${noun}`;
}

/**
 * Turn free text into a git-safe branch segment: lowercase kebab, no leading or
 * trailing dashes, capped at 50 characters. Returns "" when nothing survives —
 * callers fall back to `generateSessionName()`.
 */
export function slugifyName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 50)
    .replace(/^-+|-+$/g, "");
}

/**
 * The namespace every branch Maestro creates for itself lives under.
 *
 * Load-bearing rather than cosmetic: `list_prunable_branches` decides what it may offer to delete
 * purely from this prefix, so a branch created outside it can never be cleaned up and a branch
 * created inside it can. Both naming sites read the constant so the two cannot drift apart.
 */
export const MAESTRO_BRANCH_PREFIX = "maestro/";

/**
 * Branch name for a task's worktree. The id leads so the branch sorts and greps by task, and the
 * slug is only there to make it readable.
 */
export function taskBranchName(taskId: number, title: string): string {
  return `${MAESTRO_BRANCH_PREFIX}${taskId}-${slugifyName(title)}`;
}
