//! Re-exports wire protocol types from maestro-protocol for convenience.

pub use maestro_protocol::{
    MaestroRpcMessage, ServerRequest, ServerResponse,
    HandshakeRequest, HandshakeResponse, PROTOCOL_VERSION,
    SpawnRequest, SpawnResponse,
    PromptRequest, CancelRequest, InterruptTurnRequest,
    SessionUpdate, PermissionRequest, PermissionResponse,
    ElicitationRequest, ElicitationResponse,
    TerminalOutput, ErrorResponse,
    ListAgentsRequest, ListAgentsResponse, DiscoveredAgent,
    ModelInfo, SessionModelState,
    ModeInfo, SessionModeState,
    SetModelRequest, SetModelOkResponse,
    SetModeRequest, SetModeOkResponse,
    SetConfigOptionRequest, SetConfigOptionOkResponse, ConfigOptionUpdatedResponse,
    PromptCapabilitiesInfo,
    FileSearchRequest, FileSearchResponse, FileReadRequest, FileReadResponse,
    TurnEnded,
    SessionListRequest, SessionListOkResponse, SessionListEntry,
    SessionLoadRequest, SessionLoadOkResponse,
    SessionCloseRequest, SessionDeleteRequest,
    CheckToolsRequest, CheckToolsResponse, ToolCheckResult,
    PreInitializeRequest, PreInitializeResponse, AgentConnectionLost,
    write_message, read_message,
    MSG_LEN_SIZE, MAX_MESSAGE_SIZE,
};
