// This file was auto-generated by ts-rs 7.1
// Do not edit this file manually - regenerate using: cargo build -p gsd-demo

export type ProjectStatus = "Active" | "Archived";

export type Project = {
  id: number;
  name: string;
  path: string;
  created_at: string;
};

export type TaskStatus = "Backlog" | "Ready" | "InProgress" | "Review" | "Done";

export type Task = {
  id: number;
  project_id: number;
  name: string;
  description: string;
  acceptance_criteria?: string;
  status: TaskStatus;
  external_id?: string;
  is_imported?: boolean;
  import_source?: string;
  skills: string[];
  created_at: string;
  updated_at: string;
};

export type CreateTaskRequest = {
  project_id: number;
  name: string;
  description: string;
  acceptance_criteria: string;
  skills: string[];
};

export type WorktreeStatus = "Available" | "Leased" | "InUse" | "Dirty";

export type Worktree = {
  id: number;
  project_id: number;
  branch_name: string;
  path: string;
  status: WorktreeStatus;
  leased_at: string | null;
  returned_at: string | null;
  created_at: string;
};

export type PoolStatus = {
  total: number;
  available: number;
  leased: number;
  in_use: number;
  dirty: number;
  utilization_percent: number;
};

export type ExecutionStatus = "Running" | "Success" | "Failed" | "Cancelled";

export type ExecutionLog = {
  id: number;
  task_id: number;
  output: string;
  status: ExecutionStatus;
  started_at: string;
  completed_at: string | null;
};

export type AppSettings = {
  project_path: string | null;
  recent_projects: Array<string>;
  model_default: string;
  mcp_defaults: string | null;
  skills_defaults: string | null;
  updated_at: string;
};

export type SyncResult = {
  imported_count: number;
  updated_count: number;
  error_message?: string;
};
