// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Get list of all projects
 */
async getProjects() : Promise<Result<Project[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get list of all projects per connections
 */
async getConnectionProjects(connectionId: number | null) : Promise<Result<Project[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connection_projects", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new project
 */
async createProject(path: string, connectionId: number | null) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { path, connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get project by id
 */
async getProject(projectId: number) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * remove project by id
 */
async removeProject(projectId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize git in an existing directory (no-op if already a git repo)
 */
async gitInitProject(path: string, connectionId: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_init_project", { path, connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clone a git repository and register it as a project
 */
async cloneProject(url: string, targetPath: string, connectionId: number | null) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_project", { url, targetPath, connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new project directory, git init it, and register as a project
 */
async createNewProject(parentDir: string, folderName: string, connectionId: number | null) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_project", { parentDir, folderName, connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get list of all tasks for a project
 */
async getTasks(projectId: number) : Promise<Result<Task[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tasks", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new task with validation
 */
async createTask(projectId: number, name: string, description: string, acceptanceCriteria: string, skills: string[]) : Promise<Result<Task, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task", { projectId, name, description, acceptanceCriteria, skills }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a task's status or other fields
 */
async updateTask(taskId: number, status: string | null, description: string | null, name: string | null, priority: string | null, acceptanceCriteria: string | null, originBranch: string | null, skills: string[] | null) : Promise<Result<Task, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_task", { taskId, status, description, name, priority, acceptanceCriteria, originBranch, skills }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Archive a task by setting its archived_at timestamp
 */
async archiveTask(taskId: number) : Promise<Result<Task, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a task by id
 */
async deleteTask(taskId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get relationships for a task
 */
async getTaskRelationships(taskId: number) : Promise<Result<TaskRelationship[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_relationships", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a relationship between two tasks
 */
async addTaskRelationship(fromTaskId: number, toTaskId: number, relationshipType: string) : Promise<Result<TaskRelationship, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_task_relationship", { fromTaskId, toTaskId, relationshipType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a task relationship
 */
async removeTaskRelationship(relationshipId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_task_relationship", { relationshipId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get instructions log for a task
 */
async getTaskInstructions(taskId: number) : Promise<Result<TaskInstruction[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_instructions", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add an instruction entry to a task's log
 */
async addTaskInstruction(taskId: number, content: string, source: string) : Promise<Result<TaskInstruction, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_task_instruction", { taskId, content, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List git branches and the current branch for a project
 * 
 * Returns a tuple of (branches, current_branch).
 * Falls back to ([], "main") if the project is not a git repo or git is unavailable.
 */
async listProjectBranches(projectId: number) : Promise<Result<[string[], string], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_project_branches", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current application settings from the database
 * 
 * Loads all stored settings including project paths, default model,
 * MCP allowlist defaults, and skills defaults.
 * 
 * # Arguments
 * * `app_state` - The application state containing the database connection
 * 
 * # Returns
 * * `Result<AppSettings, String>` - The current application settings or an error message
 * 
 * # Errors
 * Returns a string error if:
 * - The database lock cannot be acquired
 * - The settings cannot be loaded from the database
 */
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save application settings to the database
 * 
 * Persists all application settings including project paths, default model,
 * MCP allowlist defaults, and skills defaults to the settings table.
 * 
 * # Arguments
 * * `app_state` - The application state containing the database connection
 * * `settings` - The application settings to persist
 * 
 * # Returns
 * * `Result<(), String>` - Success or an error message
 * 
 * # Errors
 * Returns a string error if:
 * - The database lock cannot be acquired
 * - The settings cannot be saved to the database
 */
async saveSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync issues from GitHub repository
 * 
 * Fetches open issues from a GitHub repository using the GitHub REST API and
 * imports them as tasks into the specified project. Supports both creating new
 * tasks and updating existing ones if the issue has already been imported.
 * 
 * # Arguments
 * * `state` - The application state containing the database connection
 * * `project_id` - The ID of the project to import issues into
 * * `owner` - The GitHub repository owner
 * * `repo` - The GitHub repository name
 * * `token` - A GitHub personal access token with repo read permissions
 * 
 * # Returns
 * * `Result<SyncResult, String>` - A sync result containing imported/updated counts or an error
 * 
 * # Errors
 * Returns a string error if:
 * - The GitHub API request fails
 * - The response cannot be parsed as JSON
 * - The database lock cannot be acquired
 * - A database transaction fails
 * 
 * # Implementation Details
 * - Fetches only open issues (state=open)
 * - Retrieves up to 100 issues per request
 * - Creates a database transaction to ensure atomicity
 * - Uses the issue number as the external_id
 * - Sets all imported tasks to "Backlog" status initially
 */
async syncGithubIssues(projectId: number, owner: string, repo: string, token: string) : Promise<Result<SyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_github_issues", { projectId, owner, repo, token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync issues from Jira
 * 
 * Fetches issues from a Jira instance using the Jira REST API and imports them
 * as tasks into the specified project. Supports both creating new tasks and
 * updating existing ones if the issue has already been imported.
 * 
 * # Arguments
 * * `state` - The application state containing the database connection
 * * `project_id` - The ID of the project to import issues into
 * * `host` - The Jira instance hostname (e.g., "your-instance.atlassian.net")
 * * `email` - The Jira user email for authentication
 * * `api_token` - A Jira API token for the user
 * * `jql` - A Jira Query Language (JQL) string to filter issues (e.g., "project = PROJ AND status = 'To Do'")
 * 
 * # Returns
 * * `Result<SyncResult, String>` - A sync result containing imported/updated counts or an error
 * 
 * # Errors
 * Returns a string error if:
 * - The Jira API request fails
 * - The HTTP response indicates an error
 * - The response cannot be parsed as JSON
 * - The database lock cannot be acquired
 * - A database transaction fails
 * 
 * # Implementation Details
 * - Uses HTTP Basic authentication with base64 encoded credentials
 * - Sends JQL query as a request parameter
 * - Creates a database transaction to ensure atomicity
 * - Uses the issue key (e.g., "PROJ-123") as the external_id
 * - Sets all imported tasks to "Backlog" status initially
 */
async syncJiraIssues(projectId: number, host: string, email: string, apiToken: string, jql: string) : Promise<Result<SyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_jira_issues", { projectId, host, email, apiToken, jql }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save import configuration to settings
 * 
 * Persists import provider configuration (GitHub or Jira) to the settings table
 * for later retrieval and reuse in subsequent import operations.
 * 
 * # Arguments
 * * `state` - The application state containing the database connection
 * * `project_id` - The ID of the project (for reference, not stored in config)
 * * `provider` - The import provider name ("github" or "jira")
 * * `config` - The configuration as a JSON value (provider-specific structure)
 * 
 * # Returns
 * * `Result<(), String>` - Success or an error message
 * 
 * # Errors
 * Returns a string error if:
 * - The provider is not "github" or "jira"
 * - The database lock cannot be acquired
 * - The config cannot be serialized to JSON
 * - The database INSERT fails
 * 
 * # Implementation Details
 * - Validates that provider is either "github" or "jira"
 * - Stores config as JSON string in settings table with key format: "import_config_{provider}"
 * - Uses INSERT OR REPLACE to update existing configs
 * - Records the timestamp of the save operation
 */
async saveImportConfig(projectId: number, provider: string, config: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_import_config", { projectId, provider, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorktreesWithStatus(projectId: number, repoPath: string) : Promise<Result<WorktreeWithStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees_with_status", { projectId, repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorktreeDiff(worktreeId: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worktree_diff", { worktreeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorktree(projectId: number, taskId: number | null, originBranch: string, newBranchName: string | null, repoPath: string) : Promise<Result<Worktree, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_worktree", { projectId, taskId, originBranch, newBranchName, repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWorktree(worktreeId: number, repoPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_worktree", { worktreeId, repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupZombieWorktrees(projectId: number, repoPath: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_zombie_worktrees", { projectId, repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all executions for a project, enriched with task name and worktree branch.
 * Used by the Agents View sidebar.
 */
async listExecutionsWithTaskInfo(projectId: number) : Promise<Result<ExecutionWithTask[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_executions_with_task_info", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete an execution log and clean up its PTY session if it exists.
 */
async deleteExecutionLog(executionId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_execution_log", { executionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn agent execution for a task
 */
async spawnAgentExecution(projectId: number, taskId: number, repoPath: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_agent_execution", { projectId, taskId, repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn an interactive (task-free) PTY session on a specific branch.
 * 
 * This creates an execution log with NULL task_id, finds or creates a worktree for the
 * given branch, and spawns an interactive PTY session keyed by log_id.
 * 
 * # Arguments
 * * `app_state` - Tauri app state with database connection
 * * `project_id` - Project ID
 * * `branch_name` - Branch to open in the worktree
 * * `repo_path` - Repository path
 * * `label` - Optional display label for the session
 * 
 * # Returns
 * Execution log ID (used as PTY session key for attach_terminal)
 */
async spawnInteractiveExecution(projectId: number, branchName: string, repoPath: string, label: string | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_interactive_execution", { projectId, branchName, repoPath, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drain the Ready queue for auto-mode execution
 * 
 * Checks if auto_mode is enabled in settings. If so, counts currently running
 * executions for the project and returns task IDs that should be started next,
 * up to max_concurrent_agents. Tasks are ordered by priority (Urgent, High,
 * Medium, Low) then creation date.
 * 
 * # Arguments
 * * `app_state` - Tauri app state with database connection
 * * `project_id` - Project to drain the queue for
 * * `project_path` - Repository path (reserved for future use)
 * 
 * # Returns
 * Vec of task_ids that should be executed. Frontend calls spawn_agent_execution for each.
 * Returns empty vec if auto_mode is disabled or concurrency limit is already reached.
 */
async drainReadyQueue(projectId: number, projectPath: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("drain_ready_queue", { projectId, projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get execution logs for a task
 */
async getExecutionLogs(taskId: number) : Promise<Result<ExecutionLog[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_execution_logs", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retry a paused execution
 */
async retryExecution(projectId: number, taskId: number, repoPath: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_execution", { projectId, taskId, repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a paused execution
 */
async cancelExecution(logId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_execution", { logId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Attach to a PTY session and stream output to frontend
 * 
 * Opens a Tauri channel and begins streaming PTY output to the frontend.
 * Optionally prepends terminal history from the execution log (if available).
 * The streaming continues until the PTY process ends or the channel is closed.
 * 
 * # Arguments
 * * `app_state` - Tauri app state with PTY sessions
 * * `task_id` - Task ID to attach to
 * * `output_channel` - Tauri IPC channel for streaming output
 * * `include_history` - If true, prepend terminal_output from execution log to stream
 * 
 * # Returns
 * `Result<(), String>` - Ok if streaming started, Err if task not found
 * 
 * # Behavior
 * When `include_history` is true:
 * 1. Fetches the terminal_output from the most recent execution log
 * 2. Sends entire history as initial message to establish context
 * 3. Then continues streaming live PTY output as normal
 * This ensures the frontend sees the full terminal context when attaching.
 */
async attachTerminal(taskId: number, outputChannel: TAURI_CHANNEL<string>, includeHistory: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_terminal", { taskId, outputChannel, includeHistory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send input to a PTY session
 * 
 * Writes data to the PTY master, which is delivered to the child process stdin.
 * Supports special control sequences:
 * - "\x03" (Ctrl+C) → sends SIGINT signal (interrupt) via PTY layer
 * - "\x1a" (Ctrl+Z) → sends SIGTSTP signal (suspend) via PTY layer
 * - Regular text and newlines → written directly to PTY stdin
 * 
 * The PTY layer automatically converts control sequences to signals that are
 * delivered to the foreground process group.
 * 
 * # Arguments
 * * `app_state` - Tauri app state with PTY sessions
 * * `task_id` - Task ID of the PTY session
 * * `input` - Data to send to the PTY (can be control sequences or regular text)
 * 
 * # Returns
 * `Result<(), String>` - Ok if input sent, Err if session not found or write failed
 * 
 * # Examples
 * - Regular text: "ls -la\n" → written to stdin
 * - Ctrl+C: "\x03" → converted to SIGINT by PTY layer
 * - Ctrl+Z: "\x1a" → converted to SIGTSTP by PTY layer
 */
async sendTerminalInput(taskId: number, input: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_terminal_input", { taskId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize a PTY session to new dimensions
 * 
 * Changes the terminal size and sends SIGWINCH to the PTY process.
 * Used when the frontend terminal is resized.
 * 
 * # Arguments
 * * `app_state` - Tauri app state with PTY sessions
 * * `task_id` - Task ID of the PTY session
 * * `cols` - New column width
 * * `rows` - New row height
 * 
 * # Returns
 * `Result<(), String>` - Ok if resized, Err if session not found or resize failed
 */
async resizeTerminal(taskId: number, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_terminal", { taskId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detach from a PTY session
 * 
 * Stops streaming PTY output to the frontend.
 * The actual cleanup happens when the channel is dropped on the frontend.
 * The streaming tasks in attach_terminal will exit when they detect the channel is closed.
 */
async detachTerminal(taskId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detach_terminal", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause a running agent execution by sending SIGSTOP to the process
 */
async pauseAgentExecution(taskId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_agent_execution", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume a paused agent execution by creating a new execution and spawning the agent again
 */
async resumeAgentExecution(taskId: number, projectId: number, repoPath: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_agent_execution", { taskId, projectId, repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Append terminal output to an execution log for persistence
 * 
 * Persists streamed PTY output to the database for execution history.
 * Called periodically (via tokio::time::interval) or when accumulating large chunks
 * to avoid excessive database writes.
 * 
 * # Arguments
 * * `state` - Tauri app state with database connection
 * * `task_id` - Task ID being executed
 * * `output` - Terminal output chunk to append
 * 
 * # Returns
 * `Result<(), String>` - Ok if append successful, Err on database error
 * 
 * # Behavior
 * - Appends output to most recent execution log for this task
 * - Uses COALESCE to handle NULL terminal_output gracefully
 * - Only updates logs with status 'running', 'failed', or 'complete'
 */
async appendTerminalOutput(taskId: number, output: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("append_terminal_output", { taskId, output }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get diff for review: generates unified diff between task branch and main
 * 
 * For local projects, uses git dispatcher directly.
 * For remote projects, uses git dispatcher over SSH.
 * 
 * Returns the unified diff as a string with 6 context lines.
 */
async getDiffForReview(taskId: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diff_for_review", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save task review with feedback and per-file comments
 * 
 * Creates a new review record with decision (Approve, RequestChanges, etc.)
 * and optional general feedback. Per-file comments are stored separately
 * linked to the review record.
 * 
 * Returns a typed ReviewResult with success flag and review_id.
 */
async saveTaskReview(taskId: number, decision: string, generalFeedback: string | null, perFileComments: ([string, string])[] | null) : Promise<Result<ReviewResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_task_review", { taskId, decision, generalFeedback, perFileComments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request changes on a task: saves feedback and moves task back to InProgress
 * 
 * Creates a RequestChanges review with general feedback and per-file comments,
 * then transitions the task status back to InProgress for the agent to rework.
 * 
 * Returns a typed ReviewResult with success flag, review_id, and updated task_status.
 */
async requestChanges(taskId: number, generalFeedback: string | null, perFileComments: ([string, string])[] | null) : Promise<Result<ReviewResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_changes", { taskId, generalFeedback, perFileComments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve task and perform synchronous merge to main branch
 * 
 * Orchestrates the complete merge workflow synchronously:
 * 1. Queries task details and worktree info
 * 2. Calls Node.js sidecar to perform squash merge (awaits completion)
 * 3. On success: updates task to "Done", cleans up worktree, returns to pool
 * 4. On conflict: rejects task back to "InProgress", saves conflict feedback
 * 
 * Returns a typed MergeResult with success flag, task_status, and conflicts.
 */
async approveTaskAndMerge(taskId: number, mergeStrategy: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_task_and_merge", { taskId, mergeStrategy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reject a task in review with one of three actions
 * 
 * Handles the three rejection paths from the review panel:
 * - "SendToBacklog": moves task back to Backlog status (worktree cleanup is a TODO)
 * - "ResumeWithInstructions": moves task to InProgress and saves instruction for the agent
 * - "CancelTask": moves task to Cancelled status (worktree cleanup is a TODO)
 * 
 * Returns the updated Task.
 */
async rejectReview(taskId: number, action: string, instruction: string | null) : Promise<Result<Task, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_review", { taskId, action, instruction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get project-level configuration (model default, MCP allowlist, skills default)
 * 
 * NOTE: `_project_id` is accepted for API compatibility but currently ignored.
 * Settings are stored globally in the `settings` table, not per-project.
 * Per-project settings via .maestro/settings.json is a future enhancement.
 */
async getProjectSettings(projectId: number) : Promise<Result<ProjectConfigResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_settings", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update project-level configuration
 * 
 * NOTE: `_project_id` is accepted for API compatibility but currently ignored.
 * Settings are stored globally in the `settings` table, not per-project.
 * Per-project settings via .maestro/settings.json is a future enhancement.
 */
async updateProjectSettings(projectId: number, settings: ProjectConfigRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project_settings", { projectId, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update task-level configuration overrides
 */
async updateTaskSettings(taskId: number, settings: TaskConfigRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_task_settings", { taskId, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all saved SSH connections
 */
async getSshConnections() : Promise<Result<SshConnection[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ssh_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a specific SSH connection
 */
async getSshConnection(connectionId: number) : Promise<Result<SshConnection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ssh_connection", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current connection status for a connection
 */
async getSshConnectionStatus(connectionId: number) : Promise<Result<ConnectionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ssh_connection_status", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a new SSH connection to the database
 */
async saveSshConnection(connectionString: string, authMethod: SshAuthMethod) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_ssh_connection", { connectionString, authMethod }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Attempt to connect to SSH without requiring credentials (uses saved password, agent, or key file)
 */
async connectSshWithoutCredentials(connectionId: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_ssh_without_credentials", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect to SSH using a password (fallback when credential-less connection fails)
 */
async connectSshWithPassword(connectionId: number, password: string, savePassword: boolean) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_ssh_with_password", { connectionId, password, savePassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect to SSH using the SSH agent
 */
async connectSshWithAgent(connectionId: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_ssh_with_agent", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect to SSH using a key file (with optional passphrase)
 */
async connectSshWithKey(connectionId: number, keyPath: string, passphrase: string | null, savePassphrase: boolean) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_ssh_with_key", { connectionId, keyPath, passphrase, savePassphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List directories on remote host
 */
async listRemoteDirectories(connectionId: number, path: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_remote_directories", { connectionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List subdirectories in a local filesystem path
 */
async listLocalDirectories(path: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_local_directories", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the default file picker path based on the current platform
 */
async getDefaultFilePickerPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_file_picker_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available drives (Windows only)
 */
async listDrives() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_drives") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get system accent color as RGB values
 * Returns [r, g, b] where each value is 0-255
 */
async getSystemAccentColor() : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_accent_color") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete an SSH connection from the database
 */
async deleteSshConnection(connectionId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_ssh_connection", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove saved password from OS Keyring
 */
async forgetSavedPassword(connectionId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_saved_password", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename an SSH connection (set display name)
 */
async renameSshConnection(connectionId: number, displayName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_ssh_connection", { connectionId, displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { theme_preference: string | null; auto_mode?: boolean; max_concurrent_agents?: number; updated_at: string }
/**
 * Represents the status of a remote SSH connection for a project
 */
export type ConnectionStatus = { connection_id: number; connected: boolean; disconnected_reason: string | null }
export type ErrorEvent = { error_type: string; message: string; suggestions: string[]; detected_at: string }
export type ExecutionLog = { id: number; task_id: number; output: string; terminal_output: string | null; status: ExecutionStatus; started_at: string; completed_at: string | null; error_event: ErrorEvent | null }
export type ExecutionStatus = "running" | "complete" | "failed" | "paused" | "cancelled"
/**
 * View model for the Agents view — execution log enriched with task and worktree info
 */
export type ExecutionWithTask = { id: number; task_id: number | null; task_name: string | null; branch_name: string | null; status: string; started_at: string; completed_at: string | null; terminal_output: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Typed response for approve_task_and_merge IPC command
 */
export type MergeResult = { success: boolean; task_status: string; conflicts: string[] }
export type Project = { id: number; name: string; path: string; created_at: string; updated_at: string; last_opened: string | null; connection_id: number | null }
export type ProjectConfigRequest = { model_default: string; mcp_allowlist: string[]; skills_default: string[] }
export type ProjectConfigResponse = { model_default: string; mcp_allowlist: string[]; skills_default: string[] }
/**
 * Typed response for save_task_review and request_changes IPC commands
 */
export type ReviewResult = { success: boolean; review_id: number; task_status: string | null }
/**
 * SSH authentication method configuration
 */
export type SshAuthMethod = 
/**
 * Authenticate using a private key file
 */
{ KeyFile: { path: string; save_passphrase: boolean } } | 
/**
 * Authenticate using SSH agent
 */
"Agent" | 
/**
 * Authenticate using password (stored in OS keyring)
 */
{ Password: { save_password: boolean } }
/**
 * Saved SSH connection for quick reconnection
 */
export type SshConnection = { id: number; connection_string: string; username: string; host: string; port: number; auth_method: SshAuthMethod; display_name: string | null; last_used_at: string; created_at: string }
export type SyncResult = { imported_count: number; updated_count: number; error_message?: string | null }
export type TAURI_CHANNEL<TSend> = null
export type Task = { id: number; project_id: number; name: string; description: string; acceptance_criteria?: string | null; status: TaskStatus; priority: TaskPriority; origin_branch?: string | null; archived_at?: string | null; external_id?: string | null; is_imported?: boolean | null; import_source?: string | null; skills: string[]; model_override?: string | null; mcp_allowlist?: string[] | null; skills_override?: string[] | null; created_at: string; updated_at: string }
export type TaskConfigRequest = { model_override?: string | null; mcp_allowlist?: string[] | null; skills_override?: string[] | null }
export type TaskInstruction = { id: number; task_id: number; content: string; source: string; created_at: string }
export type TaskPriority = "Urgent" | "High" | "Medium" | "Low"
export type TaskRelationship = { id: number; from_task_id: number; to_task_id: number; relationship_type: string; created_at: string }
export type TaskStatus = "Backlog" | "Ready" | "InProgress" | "Review" | "Done" | "Cancelled"
/**
 * Worktree record from database (schema v3)
 */
export type Worktree = { id: number; project_id: number; task_id: number | null; branch_name: string; path: string; git_status: string | null; created_at: string }
/**
 * View model for the Worktrees view — enriched with task info and derived status fields
 */
export type WorktreeWithStatus = { id: number | null; project_id: number | null; task_id: number | null; branch_name: string; path: string; git_status: string; created_at: string | null; task_name: string | null; agent_status: string | null; is_zombie: boolean; is_orphan: boolean; diff_stat: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
