// Re-export all handlers for use in lib.rs collect_commands!
pub use crate::project::handlers::*;
pub use crate::task::handlers::*;
pub use crate::connectivity::ssh_handlers::*;
pub use crate::connectivity::sftp_handlers::*;
pub use crate::connectivity::wsl_handlers::*;
pub use crate::connectivity::filesystem_handlers::*;
pub use crate::git::worktree_handlers::*;
pub use crate::git::review_handlers::*;
pub use crate::execution::handlers::*;
pub use crate::integration::handlers::*;
pub use crate::integration::lookup_handlers::*;
pub use crate::integration::issue_tracking_handlers::*;
pub use crate::settings::handlers::*;
pub use crate::acp::session_handlers::*;
pub use crate::acp::prompt_handlers::*;
pub use crate::acp::discovery_handlers::*;
pub use crate::acp::file_handlers::*;
pub use crate::acp::meta_handlers::*;