// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppSettings {
  project_path: string | null;
  recent_projects: Array<string>;
  model_default: string;
  mcp_allowlist: Array<string>;
  skills_default: Array<string>;
  theme_preference: string | null;
  updated_at: string;
}
