// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ConnectionStatus {
  connection_id: number;
  connected: boolean;
  disconnected_reason: string | null;
}
