// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EnhancedRecentProject { path: string, name: string, connection_id: number | null, host: string | null, username: string | null, last_opened: string, }