// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ErrorEvent { error_type: string, message: string, suggestions: Array<string>, detected_at: string, }