// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MergeOutcome {
  success: boolean;
  conflicts: Array<string>;
  conflictFiles: Array<string> | null;
  mergeCommitSha: string | null;
  message: string | null;
}
