// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PoolStatus { total: number, available: number, leased: number, in_use: number, dirty: number, utilization_percent: number, }