// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskSnapshot } from "./TaskSnapshot";
import type { WorktreeSnapshot } from "./WorktreeSnapshot";

export interface ProjectState {
  tasks: Array<TaskSnapshot>;
  worktrees: Array<WorktreeSnapshot>;
  updated_at: string;
  schema_version?: number;
}
