// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Project {
  id: number;
  name: string;
  path: string;
  created_at: string;
  updated_at: string;
  last_opened: string | null;
  connection_id: number | null;
}
