// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshConfig } from "./SshConfig";

export interface Project { id: number, name: string, path: string, created_at: string, is_remote: boolean, ssh_config: SshConfig | null, }