// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProjectConfigRequest { model_default: string, mcp_allowlist: Array<string>, skills_default: Array<string>, }