// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewDecision } from "./ReviewDecision";

export interface ReviewFeedback { id: number, task_id: number, decision: ReviewDecision, general_feedback: string | null, reviewed_at: string | null, created_at: string, }