// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ReviewComment {
  id: number;
  review_id: number;
  file_path: string;
  comment: string;
  created_at: string;
}
