// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshAuthMethod =
  | { KeyFile: { path: string } }
  | "Agent"
  | { Password: { save_password: boolean } };
