// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshAuthMethod } from "./SshAuthMethod";

export interface SshConfig { host: string, port: number, username: string, auth_method: SshAuthMethod, remote_path: string, }