// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SshConnection { id: number, connection_string: string, username: string, host: string, port: number, auth_method: string, display_name: string | null, last_used_at: string, created_at: string, }