// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SyncResult {
  imported_count: number;
  updated_count: number;
  error_message?: string;
}
