// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TaskSnapshot {
  id: number;
  name: string;
  description: string;
  status: string;
  skills: Array<string>;
  model_override?: string;
  mcp_allowlist?: Array<string>;
  skills_override?: Array<string>;
  acceptance_criteria?: string;
  external_id?: string;
  is_imported?: boolean;
  import_source?: string;
  created_at: string;
  updated_at: string;
}
