// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export interface Task {
  id: number;
  project_id: number;
  name: string;
  description: string;
  acceptance_criteria?: string;
  status: TaskStatus;
  external_id?: string;
  is_imported?: boolean;
  import_source?: string;
  skills: Array<string>;
  model_override?: string;
  mcp_allowlist?: Array<string>;
  skills_override?: Array<string>;
  created_at: string;
  updated_at: string;
}
