// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WorktreeSnapshot {
  id: number;
  branch_name: string;
  path: string;
  status: string;
  leased_at?: string;
  returned_at?: string;
  created_at: string;
}
