// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeStatus } from "./WorktreeStatus";

export interface Worktree {
  id: number;
  project_id: number;
  branch_name: string;
  path: string;
  status: WorktreeStatus;
  leased_at: string | null;
  returned_at: string | null;
  created_at: string;
}
