pub mod project;
pub mod task;
pub mod worktree;
pub mod execution_log;
pub mod settings;
pub mod sync;
pub mod review;
pub mod connection;
pub mod project_config;
pub mod project_state;
pub mod diff;

pub use project::{Project, ProjectStatus};
pub use connection::{GitConnection, ConnectionStatus};
pub use task::{Task, TaskStatus, TaskPriority, TaskRelationship, TaskInstruction, CreateTaskRequest, ProjectConfigResponse, ProjectConfigRequest, TaskConfigRequest, TASK_SELECT};
pub use worktree::{Worktree, WorktreeWithStatus, ExecutionWithTask, WORKTREE_DIR, WORKTREE_PATH_PREFIX, worktree_path_for_task};
pub use execution_log::{ExecutionLog, ExecutionStatus, ErrorEvent};
pub use settings::AppSettings;
pub use sync::{SyncResult, GitHubIssue, JiraIssue, JiraSearchResponse, JiraFields};
pub use review::{ReviewFeedback, ReviewComment, ReviewDecision, SaveReviewRequest, ReviewResult, MergeResult};
pub use project_config::ProjectConfig;
pub use project_state::{ProjectState, TaskSnapshot, WorktreeSnapshot};
pub use diff::DiffTarget;
